[project]
name = "What's Up?"
version = "0.1.0"
description = "Simple blogging platform."
authors = ["Sarah Rogue <sarah.rogue@outlook.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=4.13.0",
    "pymongo>=3.1.1",
]
